run:
  timeout: 20m

linters:
  # Start by disabling all linters so things don't change as we switch
  # golangci-lint versions. We can re-enable the ones we want below.
  disable-all: true
  enable:
    - depguard
    - errcheck
    - exhaustive
    - exptostd
    - forbidigo
    - gci
    - gocritic
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - lll
    - loggercheck
    - misspell
    - revive
    - thelper
    - unconvert
    - unused
    - unparam
    - usestdlibvars
    - usetesting
    - wsl

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        deny:
          - pkg: "io/ioutil"
            desc: "replaced by io and os packages since Go 1.16"
  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: false
    explicit-exhaustive-switch: true
    explicit-exhaustive-map: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/alcionai/clues)
    skip-generated: true
  gocritic:
    disable-all: true
    enabled-checks:
      - exitAfterDefer
  forbidigo:
    forbid:
      # Don't print, log.
      - "fmt.Print(# Is this leftover debugging? Prefer clog)?"
  lll:
    line-length: 90
  misspell:
    mode: restricted
  revive:
    max-open-files: 2048
    # Don't know why, but false means ignore generated files.
    ignore-generated-header: false
    rules:
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: constant-logical-expr
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: errorf
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: exported
      - name: identical-branches
      - name: if-return
      - name: import-shadowing
      - name: increment-decrement
      - name: indent-error-flow
      - name: modifies-value-receiver
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: redundant-import-alias
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unreachable-code
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
  thelper:
    test:
      first: true
      name: false
      begin: false
    benchmark:
      first: true
      name: false
      begin: false
    tb:
      first: true
      name: false
      begin: false
    fuzz:
      first: true
      name: false
      begin: false
  usetesting:
    # These were introduced in go1.24 so most test don't comply with them.
    context-background: false
    context-todo: false

issues:
  # Limit on number of errors with identical text reported.
  max-same-issues: 50
