package cluerr_test

import (
	"context"
	stderr "errors"
	"fmt"
	"regexp"
	"testing"

	"github.com/pkg/errors"

	"github.com/alcionai/clues/cluerr"
)

// if this panics, you added an uneven number of
// entries.  Lines should have an even number len.
// You might need to pair the line you added with
// an empty string.
func plusRE(lines ...string) string {
	var s string

	ll := len(lines)

	for i := 0; i < ll; i += 2 {
		s += lines[i]

		if len(lines[i+1]) > 0 {
			s += `\t.*/?` + lines[i+1]
		}
	}

	return s
}

type checkFmt struct {
	tmpl     string
	expect   string
	reExpect *regexp.Regexp
}

func (c checkFmt) check(t *testing.T, err error) {
	t.Run(c.tmpl, func(t *testing.T) {
		result := fmt.Sprintf(c.tmpl, err)

		if len(c.expect) > 0 && result != c.expect {
			t.Errorf(
				"unexpected fmt result for template %#v"+
					"\n\nexpected (raw)\n\"%s\""+
					"\n\ngot (raw)\n%#v"+
					"\n\ngot (fmt)\n\"%s\"",
				c.tmpl, c.expect, result, result,
			)
		}

		if c.reExpect != nil && !c.reExpect.MatchString(result) {
			t.Errorf(
				"unexpected fmt result for template %#v"+
					"\n\nexpected (raw)\n\"%s\""+
					"\n\ngot (raw)\n%#v"+
					"\n\ngot (fmt)\n\"%s\"",
				c.tmpl, c.reExpect, result, result,
			)
		}
	})
}

var errGlobalSentinel = errors.New("sentinel")

func makeOnion(base error, mid, top func(error) error) error {
	var (
		bottom = func() error { return base }
		middle = func() error { return mid(bottom()) }
		outer  = func() error { return top(middle()) }
	)

	return outer()
}

func self(err error) error { return err }

var (
	errStd     = stderr.New("an error")
	errErrs    = errors.New("an error")
	errFmtErrf = fmt.Errorf("an error")
	cluErr     = cluerr.New("an error")

	cluesWrap       = func(err error) error { return cluerr.Wrap(err, "clues wrap") }
	cluesPlainStack = func(err error) error { return cluerr.Stack(err) }
	cluesStack      = func(err error) error { return cluerr.Stack(errGlobalSentinel, err) }
)

const cluesInitFileLoc = `(<autogenerated>:\d+|.+/cluerr/.+go:?\d+)\n`

func TestFmt(t *testing.T) {
	type expect struct {
		v    string
		plus string
		hash string
		s    string
		q    string
	}

	table := []struct {
		name   string
		onion  error
		expect expect
	}{
		// ---------------------------------------------------------------------------
		// litmus
		// ---------------------------------------------------------------------------
		{
			name: "litmus wrap stderr.New",
			onion: makeOnion(errStd,
				func(err error) error { return errors.Wrap(err, "errors wrap") },
				self),
			expect: expect{
				v:    "errors wrap: an error",
				hash: "errors wrap: an error",
				s:    "errors wrap: an error",
				q:    `"errors wrap: an error"`,
				plus: plusRE(
					`an error\n`, "",
					`errors wrap\n`, "",
					`github.com/alcionai/clues/cluerr_test.TestFmt.func1\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func2\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func3\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+$`,
				),
			},
		},
		{
			name: "litmus wrap errors.New",
			onion: makeOnion(errErrs,
				func(err error) error { return errors.Wrap(err, "errors wrap") },
				self),
			expect: expect{
				v:    "errors wrap: an error",
				hash: "errors wrap: an error",
				s:    "errors wrap: an error",
				q:    `"errors wrap: an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`errors wrap\n`, "",
					`github.com/alcionai/clues/cluerr_test.TestFmt.func2\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func2\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func3\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+$`,
				),
			},
		},
		{
			name: "litmus wrap fmt.Errorf",
			onion: makeOnion(errFmtErrf,
				func(err error) error { return errors.Wrap(err, "errors wrap") },
				self),
			expect: expect{
				v:    "errors wrap: an error",
				hash: "errors wrap: an error",
				s:    "errors wrap: an error",
				q:    `"errors wrap: an error"`,
				plus: plusRE(
					`an error\n`, "",
					`errors wrap\n`, "",
					`github.com/alcionai/clues/cluerr_test.TestFmt.func3\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func2\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func3\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+$`,
				),
			},
		},
		{
			name: "litmus wrap cluerr.New",
			onion: makeOnion(cluErr,
				func(err error) error { return errors.Wrap(err, "errors wrap") },
				self),
			expect: expect{
				v:    "errors wrap: an error",
				hash: "errors wrap: an error",
				s:    "errors wrap: an error",
				q:    `"errors wrap: an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					`errors wrap\n`, "",
					`github.com/alcionai/clues/cluerr_test.TestFmt.func4\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func2\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion.func3\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.makeOnion\n`, `err_fmt_test.go:\d+\n`,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// single error
		// ---------------------------------------------------------------------------
		{
			name:  "stderr.New",
			onion: makeOnion(errStd, self, self),
			expect: expect{
				v:    "an error",
				hash: `&errors.errorString{s:"an error"}`,
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					"an error$", "",
				),
			},
		},
		{
			name:  "errors.New",
			onion: makeOnion(errErrs, self, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+$`,
				),
			},
		},
		{
			name:  "fmt.Errorf",
			onion: makeOnion(errFmtErrf, self, self),
			expect: expect{
				v:    "an error",
				hash: `&errors.errorString{s:"an error"}`,
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					"an error$", "",
				),
			},
		},
		{
			name:  "cluerr.New",
			onion: makeOnion(cluErr, self, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					"an error\n", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// wrapped error
		// ---------------------------------------------------------------------------
		{
			name:  "cluerr.Wrap stderr.New",
			onion: makeOnion(errStd, cluesWrap, self),
			expect: expect{
				v:    "clues wrap: an error",
				hash: "clues wrap: an error",
				s:    "clues wrap: an error",
				q:    `"clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Wrap errors.New",
			onion: makeOnion(errErrs, cluesWrap, self),
			expect: expect{
				v:    "clues wrap: an error",
				hash: "clues wrap: an error",
				s:    "clues wrap: an error",
				q:    `"clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.Wrap fmt.Errorf",
			onion: makeOnion(errFmtErrf, cluesWrap, self),
			expect: expect{
				v:    "clues wrap: an error",
				hash: "clues wrap: an error",
				s:    "clues wrap: an error",
				q:    `"clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`clues wrap`, "",
				),
			},
		},
		{
			name:  "cluerr.Wrap cluerr.New",
			onion: makeOnion(cluErr, cluesWrap, self),
			expect: expect{
				v:    "clues wrap: an error",
				hash: "clues wrap: an error",
				s:    "clues wrap: an error",
				q:    `"clues wrap": "an error"`,
				plus: plusRE(
					"an error\n", `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// plain stacked sentinel
		// ---------------------------------------------------------------------------
		{
			name:  "clues.PlainStack stderr.New",
			onion: makeOnion(errStd, cluesPlainStack, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.PlainStack errors.New",
			onion: makeOnion(errErrs, cluesPlainStack, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.PlainStack fmt.Errorf",
			onion: makeOnion(errFmtErrf, cluesPlainStack, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.PlainStack cluerr.New",
			onion: makeOnion(cluErr, cluesPlainStack, self),
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// stacked sentinel
		// ---------------------------------------------------------------------------
		{
			name:  "cluerr.Stack stderr.New",
			onion: makeOnion(errStd, cluesStack, self),
			expect: expect{
				v:    "sentinel: an error",
				hash: "sentinel: an error",
				s:    "sentinel: an error",
				q:    `"sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Stack errors.New",
			onion: makeOnion(errErrs, cluesStack, self),
			expect: expect{
				v:    "sentinel: an error",
				hash: "sentinel: an error",
				s:    "sentinel: an error",
				q:    `"sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.Stack fmt.Errorf",
			onion: makeOnion(errFmtErrf, cluesStack, self),
			expect: expect{
				v:    "sentinel: an error",
				hash: "sentinel: an error",
				s:    "sentinel: an error",
				q:    `"sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Stack cluerr.New",
			onion: makeOnion(cluErr, cluesStack, self),
			expect: expect{
				v:    "sentinel: an error",
				hash: "sentinel: an error",
				s:    "sentinel: an error",
				q:    `"sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// wrapped, stacked errors
		// ---------------------------------------------------------------------------
		{
			name:  "cluerr.Wrap cluerr.Stack stderr.New",
			onion: makeOnion(errStd, cluesStack, cluesWrap),
			expect: expect{
				v:    "clues wrap: sentinel: an error",
				hash: "clues wrap: sentinel: an error",
				s:    "clues wrap: sentinel: an error",
				q:    `"clues wrap": "sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Wrap cluerr.Stack errors.New",
			onion: makeOnion(errErrs, cluesStack, cluesWrap),
			expect: expect{
				v:    "clues wrap: sentinel: an error",
				hash: "clues wrap: sentinel: an error",
				s:    "clues wrap: sentinel: an error",
				q:    `"clues wrap": "sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.Wrap clues.Stack fmt.Errorf",
			onion: makeOnion(errFmtErrf, cluesStack, cluesWrap),
			expect: expect{
				v:    "clues wrap: sentinel: an error",
				hash: "clues wrap: sentinel: an error",
				s:    "clues wrap: sentinel: an error",
				q:    `"clues wrap": "sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Wrap cluerr.Stack cluerr.New",
			onion: makeOnion(cluErr, cluesStack, cluesWrap),
			expect: expect{
				v:    "clues wrap: sentinel: an error",
				hash: "clues wrap: sentinel: an error",
				s:    "clues wrap: sentinel: an error",
				q:    `"clues wrap": "sentinel": "an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// stacked, wrapped errors
		// ---------------------------------------------------------------------------
		{
			name:  "cluerr.Stack cluerr.Wrap stderr.New",
			onion: makeOnion(errStd, cluesWrap, cluesStack),
			expect: expect{
				v:    "sentinel: clues wrap: an error",
				hash: "sentinel: clues wrap: an error",
				s:    "sentinel: clues wrap: an error",
				q:    `"sentinel": "clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`clues wrap\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Stack cluerr.Wrap errors.New",
			onion: makeOnion(errErrs, cluesWrap, cluesStack),
			expect: expect{
				v:    "sentinel: clues wrap: an error",
				hash: "sentinel: clues wrap: an error",
				s:    "sentinel: clues wrap: an error",
				q:    `"sentinel": "clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "clues.Stack clues.Wrap fmt.Errorf",
			onion: makeOnion(errFmtErrf, cluesWrap, cluesStack),
			expect: expect{
				v:    "sentinel: clues wrap: an error",
				hash: "sentinel: clues wrap: an error",
				s:    "sentinel: clues wrap: an error",
				q:    `"sentinel": "clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`clues wrap\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:  "cluerr.Stack cluerr.Wrap cluerr.New",
			onion: makeOnion(cluErr, cluesWrap, cluesStack),
			expect: expect{
				v:    "sentinel: clues wrap: an error",
				hash: "sentinel: clues wrap: an error",
				s:    "sentinel: clues wrap: an error",
				q:    `"sentinel": "clues wrap": "an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					`clues wrap\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// compound stacking
		// ---------------------------------------------------------------------------
		{
			name: "multi-stack stderr.New",
			onion: cluerr.Stack(
				cluerr.Stack(
					stderr.New("top"),
					stderr.New("mid"),
				),
				cluerr.Stack(
					errGlobalSentinel,
					stderr.New("bot"),
				),
			),
			expect: expect{
				v:    "top: mid: sentinel: bot",
				hash: "top: mid: sentinel: bot",
				s:    "top: mid: sentinel: bot",
				q:    `"top": "mid": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "multi-stack errors.New",
			onion: cluerr.Stack(
				cluerr.Stack(
					errors.New("top"),
					errors.New("mid"),
				),
				cluerr.Stack(
					errGlobalSentinel,
					errors.New("bot"),
				),
			),
			expect: expect{
				v:    "top: mid: sentinel: bot",
				hash: "top: mid: sentinel: bot",
				s:    "top: mid: sentinel: bot",
				q:    `"top": "mid": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`top\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "multi-stack fmt.Errorf",
			onion: cluerr.Stack(
				cluerr.Stack(
					fmt.Errorf("top"),
					fmt.Errorf("mid"),
				),
				cluerr.Stack(
					errGlobalSentinel,
					fmt.Errorf("bot"),
				),
			),
			expect: expect{
				v:    "top: mid: sentinel: bot",
				hash: "top: mid: sentinel: bot",
				s:    "top: mid: sentinel: bot",
				q:    `"top": "mid": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "multi-stack cluerr.New",
			onion: cluerr.Stack(
				cluerr.Stack(
					cluerr.New("top"),
					cluerr.New("mid"),
				),
				cluerr.Stack(
					errGlobalSentinel,
					cluerr.New("bot"),
				),
			),
			expect: expect{
				v:    "top: mid: sentinel: bot",
				hash: "top: mid: sentinel: bot",
				s:    "top: mid: sentinel: bot",
				q:    `"top": "mid": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// wrapped, compound stacking
		// ---------------------------------------------------------------------------
		{
			name: "wrapped multi-stack stderr.New",
			onion: cluerr.Stack(
				cluerr.Wrap(cluerr.Stack(
					stderr.New("top"),
					stderr.New("mid"),
				), "lhs"),
				cluerr.Wrap(cluerr.Stack(
					errGlobalSentinel,
					stderr.New("bot"),
				), "rhs"),
			),
			expect: expect{
				v:    "lhs: top: mid: rhs: sentinel: bot",
				hash: "lhs: top: mid: rhs: sentinel: bot",
				s:    "lhs: top: mid: rhs: sentinel: bot",
				q:    `"lhs": "top": "mid": "rhs": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`rhs\n`, `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`top\n`, `err_fmt_test.go:\d+\n`,
					`lhs\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "wrapped multi-stack errors.New",
			onion: cluerr.Stack(
				cluerr.Wrap(cluerr.Stack(
					errors.New("top"),
					errors.New("mid"),
				), "lhs"),
				cluerr.Wrap(cluerr.Stack(
					errGlobalSentinel,
					errors.New("bot"),
				), "rhs"),
			),
			expect: expect{
				v:    "lhs: top: mid: rhs: sentinel: bot",
				hash: "lhs: top: mid: rhs: sentinel: bot",
				s:    "lhs: top: mid: rhs: sentinel: bot",
				q:    `"lhs": "top": "mid": "rhs": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`rhs\n`, `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`top\n`, ``,
					`github.com/alcionai/clues/cluerr_test.TestFmt\n`, `err_fmt_test.go:\d+\n`,
					`testing.tRunner\n`, `testing.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`lhs\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "wrapped multi-stack fmt.Errorf",
			onion: cluerr.Stack(
				cluerr.Wrap(cluerr.Stack(
					fmt.Errorf("top"),
					fmt.Errorf("mid"),
				), "lhs"),
				cluerr.Wrap(cluerr.Stack(
					errGlobalSentinel,
					fmt.Errorf("bot"),
				), "rhs"),
			),
			expect: expect{
				v:    "lhs: top: mid: rhs: sentinel: bot",
				hash: "lhs: top: mid: rhs: sentinel: bot",
				s:    "lhs: top: mid: rhs: sentinel: bot",
				q:    `"lhs": "top": "mid": "rhs": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, ``,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`rhs\n`, `err_fmt_test.go:\d+\n`,
					`mid\n`, ``,
					`top\n`, `err_fmt_test.go:\d+\n`,
					`lhs\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name: "wrapped multi-stack cluerr.New",
			onion: cluerr.Stack(
				cluerr.Wrap(cluerr.Stack(
					cluerr.New("top"),
					cluerr.New("mid"),
				), "lhs"),
				cluerr.Wrap(cluerr.Stack(
					errGlobalSentinel,
					cluerr.New("bot"),
				), "rhs"),
			),
			expect: expect{
				v:    "lhs: top: mid: rhs: sentinel: bot",
				hash: "lhs: top: mid: rhs: sentinel: bot",
				s:    "lhs: top: mid: rhs: sentinel: bot",
				q:    `"lhs": "top": "mid": "rhs": "sentinel": "bot"`,
				plus: plusRE(
					`bot\n`, `err_fmt_test.go:\d+\n`,
					`sentinel\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`rhs\n`, `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`lhs\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
	}
	for _, test := range table {
		t.Run(test.name, func(t *testing.T) {
			formats := []checkFmt{
				{"%v", test.expect.v, nil},
				{"%+v", "", regexp.MustCompile(test.expect.plus)},
				{"%#v", test.expect.hash, nil},
				{"%s", test.expect.s, nil},
				{"%q", test.expect.q, nil},
			}

			for _, f := range formats {
				f.check(t, test.onion)
			}
		})
	}
}

// wrapped

func bottomWrap(err error) error {
	return cluerr.Wrap(err, "bottom wrap")
}

func midWrap(err error) error {
	return cluerr.Wrap(bottomWrap(err), "mid wrap")
}

func topWrap(err error) error {
	return cluerr.Wrap(midWrap(err), "top wrap")
}

// plain-stacked

func bottomPlainStack(err error) error {
	return cluerr.Stack(err)
}

func midPlainStack(err error) error {
	return cluerr.Stack(bottomPlainStack(err))
}

func topPlainStack(err error) error {
	return cluerr.Stack(midPlainStack(err))
}

// stacked

func bottomStack(err error) error {
	return cluerr.Stack(cluerr.New("bottom"), err)
}

func midStack(err error) error {
	return cluerr.Stack(cluerr.New("mid"), bottomStack(err))
}

func topStack(err error) error {
	return cluerr.Stack(cluerr.New("top"), midStack(err))
}

func TestFmt_nestedFuncs(t *testing.T) {
	type expect struct {
		v    string
		plus string
		hash string
		s    string
		q    string
	}

	table := []struct {
		name   string
		fn     func(error) error
		source error
		expect expect
	}{
		// ---------------------------------------------------------------------------
		// wrapped error
		// ---------------------------------------------------------------------------
		{
			name:   "cluerr.Wrap stderr.New",
			fn:     topWrap,
			source: errStd,
			expect: expect{
				v:    "top wrap: mid wrap: bottom wrap: an error",
				hash: "top wrap: mid wrap: bottom wrap: an error",
				s:    "top wrap: mid wrap: bottom wrap: an error",
				q:    `"top wrap": "mid wrap": "bottom wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`bottom wrap\n`, `err_fmt_test.go:\d+\n`,
					`mid wrap\n`, `err_fmt_test.go:\d+\n`,
					`top wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Wrap errors.New",
			fn:     topWrap,
			source: errErrs,
			expect: expect{
				v:    "top wrap: mid wrap: bottom wrap: an error",
				hash: "top wrap: mid wrap: bottom wrap: an error",
				s:    "top wrap: mid wrap: bottom wrap: an error",
				q:    `"top wrap": "mid wrap": "bottom wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`bottom wrap\n`, `err_fmt_test.go:\d+\n`,
					`mid wrap\n`, `err_fmt_test.go:\d+\n`,
					`top wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Wrap fmt.Errorf",
			fn:     topWrap,
			source: errFmtErrf,
			expect: expect{
				v:    "top wrap: mid wrap: bottom wrap: an error",
				hash: "top wrap: mid wrap: bottom wrap: an error",
				s:    "top wrap: mid wrap: bottom wrap: an error",
				q:    `"top wrap": "mid wrap": "bottom wrap": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`bottom wrap\n`, `err_fmt_test.go:\d+\n`,
					`mid wrap\n`, `err_fmt_test.go:\d+\n`,
					`top wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Wrap cluerr.New",
			fn:     topWrap,
			source: cluErr,
			expect: expect{
				v:    "top wrap: mid wrap: bottom wrap: an error",
				hash: "top wrap: mid wrap: bottom wrap: an error",
				s:    "top wrap: mid wrap: bottom wrap: an error",
				q:    `"top wrap": "mid wrap": "bottom wrap": "an error"`,
				plus: plusRE(
					"an error\n", `err_fmt_test.go:\d+\n`,
					`bottom wrap\n`, `err_fmt_test.go:\d+\n`,
					`mid wrap\n`, `err_fmt_test.go:\d+\n`,
					`top wrap\n`, `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// plain stacked
		// ---------------------------------------------------------------------------
		{
			name:   "clues.PlainStack stderr.New",
			fn:     topPlainStack,
			source: errStd,
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, "",
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "clues.PlainStack errors.New",
			fn:     topPlainStack,
			source: errErrs,
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "clues.PlainStack fmt.Errorf",
			fn:     topPlainStack,
			source: errFmtErrf,
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, "",
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "clues.PlainStack cluerr.New",
			fn:     topPlainStack,
			source: cluErr,
			expect: expect{
				v:    "an error",
				hash: "an error",
				s:    "an error",
				q:    `"an error"`,
				plus: plusRE(
					`an error\n`, ``,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		// ---------------------------------------------------------------------------
		// stacked tree
		// ---------------------------------------------------------------------------
		{
			name:   "cluerr.Stack stderr.New",
			fn:     topStack,
			source: errStd,
			expect: expect{
				v:    "top: mid: bottom: an error",
				hash: "top: mid: bottom: an error",
				s:    "top: mid: bottom: an error",
				q:    `"top": "mid": "bottom": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`bottom\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Stack errors.New",
			fn:     topStack,
			source: errErrs,
			expect: expect{
				v:    "top: mid: bottom: an error",
				hash: "top: mid: bottom: an error",
				s:    "top: mid: bottom: an error",
				q:    `"top": "mid": "bottom": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`github.com/alcionai/clues/cluerr_test.init\n`, cluesInitFileLoc,
					`runtime.doInit1?\n`, `proc.go:\d+\n`,
					`runtime.doInit\n`, `proc.go:\d+\n`,
					`runtime.main\n`, `proc.go:\d+\n`,
					`runtime.goexit\n`, `runtime/.*:\d+\n`,
					`bottom\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Stack fmt.Errorf",
			fn:     topStack,
			source: errFmtErrf,
			expect: expect{
				v:    "top: mid: bottom: an error",
				hash: "top: mid: bottom: an error",
				s:    "top: mid: bottom: an error",
				q:    `"top": "mid": "bottom": "an error"`,
				plus: plusRE(
					`an error\n`, "",
					`bottom\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
		{
			name:   "cluerr.Stack cluerr.New",
			fn:     topStack,
			source: cluErr,
			expect: expect{
				v:    "top: mid: bottom: an error",
				hash: "top: mid: bottom: an error",
				s:    "top: mid: bottom: an error",
				q:    `"top": "mid": "bottom": "an error"`,
				plus: plusRE(
					`an error\n`, `err_fmt_test.go:\d+\n`,
					`bottom\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`mid\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+\n`,
					`top\n`, `err_fmt_test.go:\d+\n`,
					"", `err_fmt_test.go:\d+$`,
				),
			},
		},
	}
	for _, test := range table {
		t.Run(test.name, func(t *testing.T) {
			formats := []checkFmt{
				{"%v", test.expect.v, nil},
				{"%+v", "", regexp.MustCompile(test.expect.plus)},
				{"%#v", test.expect.hash, nil},
				{"%s", test.expect.s, nil},
				{"%q", test.expect.q, nil},
			}

			for _, f := range formats {
				f.check(t, test.fn(test.source))
			}
		})
	}
}

func TestSkipCaller(t *testing.T) {
	table := []struct {
		name          string
		tracer        func(err error) error
		expect        string
		expectWrapped string
		expectStacked string
	}{
		{
			name: "error -1",
			tracer: func(err error) error {
				return withSkipCaller(err, -1)
			},
			expect: plusRE(`an error\n`, `err_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`an error\n`, `err_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "error 0",
			tracer: func(err error) error {
				return withSkipCaller(err, 0)
			},
			expect: plusRE(`an error\n`, `err_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`an error\n`, `err_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "error 1",
			tracer: func(err error) error {
				return withSkipCaller(err, 1)
			},
			expect: plusRE(`an error\n`, `err_fmt_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`an error\n`, `err_fmt_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "error 2",
			tracer: func(err error) error {
				return withSkipCaller(err, 2)
			},
			expect: plusRE(`an error\n`, `err_fmt_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`an error\n`, `err_fmt_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "error 3",
			tracer: func(err error) error {
				return withSkipCaller(err, 3)
			},
			expect: plusRE(`an error\n`, `testing/testing.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `testing/testing.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `testing/testing.go:\d+\n`,
				`an error\n`, `testing/testing.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "error 4",
			tracer: func(err error) error {
				return withSkipCaller(err, 4)
			},
			expect: plusRE(`an error\n`, `runtime/.*:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `runtime/.*:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `runtime/.*:\d+\n`,
				`an error\n`, `runtime/.*:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
	}
	for _, test := range table {
		t.Run(test.name, func(t *testing.T) {
			t.Run("plain error", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expect)}.
					check(t, test.tracer(cluErr))
			})
			t.Run("wrapWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.WrapWC(context.Background(), test.tracer(cluErr), "wrap"))
			})
			t.Run("wrap", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.Wrap(test.tracer(cluErr), "wrap"))
			})
			t.Run("stackWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.StackWC(context.Background(), cluErr, test.tracer(cluErr)))
			})
			t.Run("stack", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.Stack(cluErr, test.tracer(cluErr)))
			})
		})
	}

	table2 := []struct {
		name          string
		tracer        func(err *cluerr.Err) error
		expect        string
		expectWrapped string
		expectStacked string
	}{
		{
			name: "cluerr.Err 1",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, -1)
			},
			expect: plusRE(`an error\n`, `err_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`an error\n`, `err_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err 0",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, 0)
			},
			expect: plusRE(`an error\n`, `err_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_test.go:\d+\n`,
				`an error\n`, `err_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err 1",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, 1)
			},
			expect: plusRE(`an error\n`, `err_fmt_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`an error\n`, `err_fmt_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err 2",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, 2)
			},
			expect: plusRE(`an error\n`, `err_fmt_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `err_fmt_test.go:\d+\n`,
				`an error\n`, `err_fmt_test.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err 3",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, 3)
			},
			expect: plusRE(`an error\n`, `testing/testing.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `testing/testing.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `testing/testing.go:\d+\n`,
				`an error\n`, `testing/testing.go:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err 4",
			tracer: func(err *cluerr.Err) error {
				return cluesWithSkipCaller(err, 4)
			},
			expect: plusRE(`an error\n`, `runtime/.*:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, `runtime/.*:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, `runtime/.*:\d+\n`,
				`an error\n`, `runtime/.*:\d+\n`,
				``, `err_fmt_test.go:\d+$`),
		},
	}

	for _, test := range table2 {
		t.Run(test.name, func(t *testing.T) {
			t.Run("plain error", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expect)}.
					check(t, test.tracer(cluErr))
			})
			t.Run("wrapWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.WrapWC(context.Background(), test.tracer(cluErr), "wrap"))
			})
			t.Run("wrap", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.Wrap(test.tracer(cluErr), "wrap"))
			})
			t.Run("stackWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.StackWC(context.Background(), cluErr, test.tracer(cluErr)))
			})
			t.Run("stack", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.Stack(cluErr, test.tracer(cluErr)))
			})
		})
	}

	table3 := []struct {
		name          string
		tracer        func(err *cluerr.Err) error
		expect        string
		expectWrapped string
		expectStacked string
	}{
		{
			name: "cluerr.Err wrapped with generic",
			tracer: func(err *cluerr.Err) error {
				return wrapWithFuncWithGeneric(err)
			},
			expect: plusRE(
				`an error\n`, ``,
				`with-generic\n`, `wrapWithFuncWithGeneric - .*err_test.go:\d+$`),
			expectWrapped: plusRE(
				`an error\n`, ``,
				`with-generic\n`, `wrapWithFuncWithGeneric - .*err_test.go:\d+\n`,
				`wrap\n`, `err_fmt_test.go:\d+$`),
			expectStacked: plusRE(
				`an error\n`, ``,
				`with-generic\n`, `wrapWithFuncWithGeneric - .*err_test.go:\d+\n`,
				`an error\n`, `err_fmt_test.go:\d+$`),
		},
		{
			name: "cluerr.Err wrapped with no trace",
			tracer: func(err *cluerr.Err) error {
				return withNoTrace(err)
			},
			expect: plusRE(
				`an error\n`, ``,
				`no-trace`, ``),
			expectWrapped: plusRE(
				`an error\n`, ``,
				`no-trace\n`, ``),
			expectStacked: plusRE(
				`an error\n`, ``,
				`no-trace\n`, ``,
				`an error\n`, `err_fmt_test.go:\d+$`),
		},
	}

	for _, test := range table3 {
		t.Run(test.name, func(t *testing.T) {
			err := cluErr.NoTrace()

			t.Run("plain error", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expect)}.
					check(t, test.tracer(err))
			})
			t.Run("wrapWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.WrapWC(context.Background(), test.tracer(err), "wrap"))
			})
			t.Run("wrap", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectWrapped)}.
					check(t, cluerr.Wrap(test.tracer(err), "wrap"))
			})
			t.Run("stackWC", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.StackWC(context.Background(), err, test.tracer(err)))
			})
			t.Run("stack", func(t *testing.T) {
				checkFmt{"%+v", "", regexp.MustCompile(test.expectStacked)}.
					check(t, cluerr.Stack(err, test.tracer(err)))
			})
		})
	}
}

func TestComment(t *testing.T) {
	table := []struct {
		name          string
		commenter     func(err error) error
		expect        string
		expectWrapped string
		expectStacked string
	}{
		{
			name: "error flat comment",
			commenter: func(err error) error {
				return withCommentWrapper(err, "fisher")
			},
			expect: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
			expectWrapped: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
			expectStacked: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`withCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
		},
		{
			name: "error formatted comment",
			commenter: func(err error) error {
				return withCommentWrapper(err, "%d", 42)
			},
			expect: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `42`,
				`withCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
			expectWrapped: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `42`,
				`withCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
			expectStacked: commentRE(
				`withCommentWrapper`, `cluerr/err_test.go`, `42`,
				`withCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
		},
	}
	for _, test := range table {
		t.Run(test.name, func(t *testing.T) {
			t.Run("plain error", func(t *testing.T) {
				comments := cluerr.Comments(test.commenter(cluErr)).String()
				commentMatches(t, test.expect, comments)
			})
			t.Run("wrapWC", func(t *testing.T) {
				err := cluerr.WrapWC(context.Background(), test.commenter(cluErr), "wrap")
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectWrapped, comments)
			})
			t.Run("wrap", func(t *testing.T) {
				err := cluerr.Wrap(test.commenter(cluErr), "wrap")
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectWrapped, comments)
			})
			t.Run("stackWC", func(t *testing.T) {
				err := cluerr.StackWC(context.Background(), cluErr, test.commenter(cluErr))
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectStacked, comments)
			})
			t.Run("stack", func(t *testing.T) {
				err := cluerr.Stack(cluErr, test.commenter(cluErr))
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectStacked, comments)
			})
		})
	}

	table2 := []struct {
		name          string
		commenter     func(err *cluerr.Err) error
		expect        string
		expectWrapped string
		expectStacked string
	}{
		{
			name: "cluerr.Err flat comment",
			commenter: func(err *cluerr.Err) error {
				return cluerrWithCommentWrapper(err, "fisher")
			},
			expect: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
			expectWrapped: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
			expectStacked: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `fisher - repeat$`),
		},
		{
			name: "cluerr.Err formatted comment",
			commenter: func(err *cluerr.Err) error {
				return cluerrWithCommentWrapper(err, "%d", 42)
			},
			expect: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
			expectWrapped: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
			expectStacked: commentRE(
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42`,
				`cluerrWithCommentWrapper`, `cluerr/err_test.go`, `42 - repeat$`),
		},
	}

	for _, test := range table2 {
		t.Run(test.name, func(t *testing.T) {
			t.Run("plain error", func(t *testing.T) {
				comments := cluerr.Comments(test.commenter(cluErr)).String()
				commentMatches(t, test.expect, comments)
			})
			t.Run("wrapWC", func(t *testing.T) {
				err := cluerr.WrapWC(context.Background(), test.commenter(cluErr), "wrap")
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectWrapped, comments)
			})
			t.Run("wrap", func(t *testing.T) {
				err := cluerr.Wrap(test.commenter(cluErr), "wrap")
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectWrapped, comments)
			})
			t.Run("stackWC", func(t *testing.T) {
				err := cluerr.StackWC(context.Background(), cluErr, test.commenter(cluErr))
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectStacked, comments)
			})
			t.Run("stack", func(t *testing.T) {
				err := cluerr.Stack(cluErr, test.commenter(cluErr))
				comments := cluerr.Comments(err).String()
				commentMatches(t, test.expectStacked, comments)
			})
		})
	}
}

func TestErrCore_String(t *testing.T) {
	table := []struct {
		name        string
		core        *cluerr.ErrCore
		expectS     string
		expectVPlus string
	}{
		{
			name:        "nil",
			core:        nil,
			expectS:     `<nil>`,
			expectVPlus: `<nil>`,
		},
		{
			name: "all values",
			core: cluerr.
				New("message").
				With("key", "value").
				Label("label").
				Core(),
			expectS:     `{"message", [label], {key:value}}`,
			expectVPlus: `{msg:"message", labels:[label], values:{key:value}, comments:[]}`,
		},
		{
			name: "message only",
			core: cluerr.
				New("message").
				Core(),
			expectS:     `{"message"}`,
			expectVPlus: `{msg:"message", labels:[], values:{}, comments:[]}`,
		},
		{
			name: "labels only",
			core: cluerr.
				New("").
				Label("label").
				Core(),
			expectS:     `{[label]}`,
			expectVPlus: `{msg:"", labels:[label], values:{}, comments:[]}`,
		},
		{
			name: "values only",
			core: cluerr.
				New("").
				With("key", "value").
				Core(),
			expectS:     `{{key:value}}`,
			expectVPlus: `{msg:"", labels:[], values:{key:value}, comments:[]}`,
		},
	}
	for _, test := range table {
		t.Run(test.name, func(t *testing.T) {
			tc := test.core
			if tc != nil {
				if _, ok := tc.Values["clues_trace"]; ok {
					t.Errorf(
						"did not expect core values to contain key [clues_trace]\ngot: %+v",
						tc.Values)
				}

				delete(tc.Values, "clues_trace")
			}

			result := tc.String()
			if result != test.expectS {
				t.Errorf("expected string\n%s\ngot %s", test.expectS, result)
			}

			result = fmt.Sprintf("%s", test.core)
			if result != test.expectS {
				t.Errorf("expected %%s\n%s\ngot %s", test.expectS, result)
			}

			result = fmt.Sprintf("%v", test.core)
			if result != test.expectS {
				t.Errorf("expected %%s\n%s\ngot %s", test.expectS, result)
			}

			result = fmt.Sprintf("%+v", test.core)
			if result != test.expectVPlus {
				t.Errorf("expected %%s\n%s\ngot %s", test.expectVPlus, result)
			}

			result = fmt.Sprintf("%#v", test.core)
			if result != test.expectVPlus {
				t.Errorf("expected %%s\n%s\ngot %s", test.expectVPlus, result)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// requires sets of 3 strings
func commentRE(ss ...string) string {
	result := ""

	for i := 0; i < len(ss); i += 3 {
		result += ss[i] + " - "
		result += ss[i+1] + `:\d+\n`
		result += `\t` + ss[i+2]

		if len(ss) > i+3 {
			result += `\n`
		}
	}

	return result
}

func commentMatches(
	t *testing.T,
	expect, result string,
) {
	re := regexp.MustCompile(expect)

	if !re.MatchString(result) {
		t.Errorf(
			"unexpected comments stack"+
				"\n\nexpected (raw)\n\"%s\""+
				"\n\ngot (raw)\n%#v"+
				"\n\ngot (fmt)\n\"%s\"",
			re, result, result)
	}
}
